- docs/2.0/associations/belongs_to.md
- docs/2.0/associations/has_and_belongs_to_many.md
- docs/2.0/associations/has_many.md
- docs/2.0/common/associations_hide_search_input_option_common.md
- docs/2.0/common/associations_searchable_option_common.md
- docs/2.0/common/search_query_scope_common.md
- docs/2.0/resources.md
- docs/2.0/search.md
- docs/2.0/upgrade.md
> scoped search queries

- docs/2.0/customizable-controls.md
> warning actions arguments

- docs/2.0/upgrade.md
> locales update upgrade guide

- docs/2.0/upgrade.md
> upgrade guide 2.28

- docs/2.0/field-options.md
hey guys, I missed this example in the docs, so I am adding it
> show how to use rails helpers

- docs/2.0/common/file_options_common.md
> display filename

- docs/2.0/customization.md
- docs/2.0/upgrade.md
> change index cache default as false

- docs/2.0/authorization.md
- docs/3.0/authorization.md
- docs/3.0/upgrade.md
> inherit_association_from_policy

- docs/2.0/field-options.md
- docs/2.0/upgrade.md
- docs/3.0/field-options.md
> warning: fields visible block

- docs/.vitepress/config.js
> controllers revision

- docs/3.0/actions.md
- docs/3.0/basic-filters.md
- docs/3.0/customizable-controls.md
- docs/3.0/resources.md
- docs/3.0/scopes.md
https://github.com/avo-hq/avo-3/pull/289
> refactor: resource actions scopes and filters api

- docs/2.0/customization.md
The skip_default_view options returns undefined method.
> Fix description and code snippet to skip show page

- docs/3.0/basic-filters.md
- docs/3.0/cards.md
- docs/3.0/dashboards.md
https://github.com/avo-hq/avo-3/pull/298
> refactor: uniform generators

- docs/2.0/field-options.md
> Correct typo

- docs/2.0/fields/location.md
See https://github.com/avo-hq/avo/pull/1835 for details
> Added documentation for zoom to the location field

- docs/2.0/native-components/avo-panel-component.md
Adding basic documentation for new `bare_sidebar` option https://github.com/avo-hq/avo/pull/1863
> add with_bare_sidebar option to panel component

- docs/3.0/fields/select.md
- docs/3.0/upgrade.md
Fixes https://github.com/avo-hq/avo-3/issues/318
> improve: select field && upgrade guide

- docs/3.0/fields/badge.md
Added new secondary badge option as mentioned in issue https://github.com/avo-hq/avo/issues/1909
> feature: Updated secondary badge details for version 3.0

- docs/3.0/avo-2-avo-3-upgrade.md
- docs/3.0/common/link_to_record_common.md
- docs/3.0/custom-fields.md
- docs/3.0/field-options.md
- docs/3.0/fields/external_image.md
- docs/3.0/fields/file.md
- docs/3.0/fields/gravatar.md
- docs/3.0/fields/id.md
- docs/3.0/fields/text.md
- docs/3.0/gemfile-environment-variables.md
- docs/3.0/resource-sidebar.md
- docs/3.0/resources.md
- docs/3.0/tabs.md
From https://github.com/avo-hq/avo-3/pull/386
> refactor: rename link_to_resource to link_to_record

- docs/3.0/actions.md
From https://github.com/avo-hq/avo-3/pull/387
> alias query as records on actions

- docs/3.0/fields.md
- yarn.lock
https://github.com/avo-hq/avo-3/pull/392
> feature: resource fields methods for each view

- docs/2.0/cache.md
- docs/2.0/upgrade.md
https://github.com/avo-hq/avo/pull/1983
> add: custom cache store

- docs/3.0/dynamic-filters.md
https://github.com/avo-hq/avo-dynamic_filters/pull/9
> feature: array dynamic filter

- docs/2.0/actions.md
- docs/3.0/actions.md
https://github.com/avo-hq/avo-3/pull/439
> add: multiple action flux

- docs/3.0/upgrade.md
https://github.com/avo-hq/avo-3/pull/442
> refactor: remove attachments eager load

- docs/3.0/actions.md
- docs/3.0/upgrade.md
https://github.com/avo-hq/avo/issues/1989
> feature: action authorization

- docs/3.0/upgrade.md
https://github.com/avo-hq/avo-dashboards/pull/23
https://github.com/avo-hq/avo-dashboards/issues/22
> fix: dashboards visibility and authorization

- docs/3.0/customization.md
For PR https://github.com/avo-hq/avo/pull/2067
> feature: logger

- docs/3.0/actions.md
> fix: action arguments

- docs/3.0/actions.md
https://github.com/avo-hq/avo/pull/2345
> feature: close_modal

- docs/3.0/custom-asset-pipeline.md
From here -> https://discord.com/channels/740892036978442260/1194684399350988844
> CDN assets

- docs/3.0/testing.md
A small fixes to testing actions guides
> Fixes testing actions with avo 3.0

- docs/3.0/dashboards.md
Changed self.authorization to self.authorize, in order to accurately reflect the BaseDashboard class.
> Update dashboards.md authorization section

- docs/3.0/actions.md
- docs/3.0/customization.md
- docs/3.0/upgrade.md
https://github.com/avo-hq/avo/pull/2465
> chore: add turbo 8 changes

- docs/3.0/fields/boolean_group.md
Update docs for avo-hq/avo#2679.
> Add computed options to boolean group

- docs/3.0/fields/boolean_group.md
Updates docs according to avo-hq/avo#2677.
> Remove override warning from boolean group

- docs/3.0/dynamic-filters.md
https://github.com/avo-hq/avo/issues/2680#issuecomment-2051872847
> Added a warning message for ransackable_attributes

- docs/3.0/cache.md
related to this: https://github.com/avo-hq/avodocs/pull/186
https://discord.com/channels/740892036978442260/1234796408175853649/1234873855450022020
> Add solutions for caching issue in Avo project

- docs/3.0/actions.md
[Add docs about passing params to the action show page](https://github.com/avo-hq/docs.avohq.io/issues/209)
> Add documentation for passing params to action show page

- docs/3.0/views.md
Fix: https://github.com/avo-hq/docs.avohq.io/issues/212
> Add display and form view types

- docs/3.0/search.md
Add docs for configuring search_results_count on individual resources.
> Add docs for search results count

- docs/3.0/resource-panels.md
Adding documentation for the new `visible` option for `panel`
Corresponding PR: https://github.com/avo-hq/avo/pull/2989
> Add docs for `visible` option for `panel`

- docs/3.0/resources.md
Description for extending Avo::BaseResource allowing customization 
feature pr for the same can be found here : [pull request](https://github.com/avo-hq/avo/pull/2998)
> Documentation || Extending Avo::BaseResource

- docs/3.0/guides/format-ruby-object-to-json.md
Hi, 
I am using this, and I hope it will be handy for everyone. 
Let me know if you would need any updates from my side.
> Add DRY solution for JSON fields

- docs/3.0/search.md
Fixes https://github.com/avo-hq/avo/issues/3012
> custom search results

- docs/3.0/dynamic-filters.md
Fixes https://github.com/avo-hq/avo/issues/3026
> Options for select

- docs/.vitepress/config.js
- docs/3.0/custom-errors.md
https://github.com/avo-hq/avo/pull/3002
> custom errors

- docs/3.0/guides/acts_as_tenant_integration.md
Add documentation for Acts As Tenant integration
> Add documentation for Acts As Tenant integration

- docs/3.0/tabs.md
Fixes https://github.com/avo-hq/docs.avohq.io/issues/265 and https://github.com/avo-hq/docs.avohq.io/issues/250
> Add docs for visibility control for `tabs` and `tab`

- docs/3.0/resources.md
Fixes https://github.com/avo-hq/docs.avohq.io/issues/251
> Add docs for `default_sort_column` for resource

- docs/3.0/authorization.md
Fixes https://github.com/avo-hq/avo/issues/2125
> implicit_authorization

- docs/3.0/authorization.md
- docs/3.0/upgrade.md
Fixes https://github.com/avo-hq/avo/issues/3348
> refactor: rename `implicit_authorization` to `explicit_authorization`

- docs/3.0/plugins.md
Just saw this typo while skimming through the docs and thought I'll open a PR to fix it 🙌🏼
> Fix typo in plugins docs

- docs/3.0/basic-filters.md
Fixes https://github.com/avo-hq/avo/issues/3244
> feature: callable filter name

- docs/3.0/actions.md
Fixes https://github.com/avo-hq/avo/issues/3326
Related PR: https://github.com/avo-hq/avo/pull/3379
> feature: action dynamic backdrop option

- docs/3.0/actions.md
PR: https://github.com/avo-hq/avo/pull/3372
Fixes https://github.com/avo-hq/avo/issues/3345
> reload_records

- docs/3.0/dynamic-filters.md
Fixes https://github.com/avo-hq/docs.avohq.io/issues/275
> add default conditions hash for dynamic filters

- docs/3.0/customization.md
- docs/3.0/upgrade.md
Reverts avo-hq/docs.avohq.io#326
> Revert "cache_associations_pagination"

- docs/3.0/fields/location.md
Fix: https://github.com/avo-hq/avo/issues/3147
> Add documentation to location field

- docs/.vitepress/config.js
- docs/3.0/internal-model-names.md
Fixes https://github.com/avo-hq/docs.avohq.io/issues/328
Fixes https://github.com/avo-hq/avo/issues/3586
> Reserved model names and routes

- docs/3.0/tailwind-4-migration.md
- docs/3.0/upgrade.md
Fixes https://github.com/avo-hq/docs.avohq.io/issues/360
> tw4 custom pipeline

- docs/3.0/guides/attachment-policy-extension-for-pundit.md
A helper method to help people using Pundit enable / disable file manipulation
> 💬 Add Attachment Policy Extension for Pundit

- docs/3.0/customizable-controls.md
> add `include` option for `actions_list`

- docs/3.0/dynamic-filters.md
- docs/4.0/dynamic-filters.md
Fixes https://github.com/avo-hq/docs.avohq.io/issues/266
> associations filters example

- docs/3.0/customization.md
- docs/4.0/customization.md
fixes https://github.com/avo-hq/docs.avohq.io/issues/293
> first_sorting_option

- docs/3.0/dynamic-filters.md
- docs/4.0/dynamic-filters.md
Fixes https://github.com/avo-hq/docs.avohq.io/issues/299
> multiple filters combination logic

- docs/3.0/actions/execution.md
- docs/4.0/actions/execution.md
Add docs for https://github.com/avo-hq/avo/pull/3935
> Add timeout option for feedback notifications toasts

- docs/3.0/customization.md
- docs/4.0/customization.md
- docs/public/llms.txt
> exclude_from_status

- docs/3.0/scopes.md
- docs/4.0/scopes.md
- docs/public/llms.txt
> Scopes options

- docs/3.0/dynamic-filters.md
- docs/4.0/dynamic-filters.md
Fixes https://github.com/avo-hq/avo-dynamic_filters/issues/92
> fetch_values_from value dynamic filter

- docs/3.0/fields/external_image.md
- docs/3.0/upgrade.md
- docs/4.0/fields/external_image.md
Related to https://github.com/avo-hq/avo/pull/3941
> update external image

- docs/3.0/dynamic-filters.md
- docs/4.0/dynamic-filters.md
Fixes  https://github.com/avo-hq/avo-dynamic_filters/issues/93
> add composable filters guide

- docs/3.0/actions/execution.md
- docs/4.0/actions/execution.md
Added a section about fields in actions, explaining their usage and relation to records.
ref: #450
> Add section on fields in action execution

- docs/3.0/fields.md
- docs/4.0/fields.md
> Enhance fields documentation with Actions usage
