avo-hq/docs.avohq.io

docs/2.0/records-reordering.md
They shouldn't take a record parameter. The example further up the page is correct, but this example doesn't work.
=> Made sure sort actions are not passed a record

docs/2.0/actions.md
When I wrote my own actions it wasn’t clear to me how to redirect to a page within avo. I’ve updated the docs to show how to access routes from the avo engine.
=> Use route helpers in actions documentation

docs/2.0/authentication.md
This change is associated with avo-hq/avo#1408
While I was adding the documentation for `sign_out_path_name` I also tried to clarify the documentation for `current_user_resource_name` and fix the examples in that section to the best of my understanding.
=> Add documentation for sign_out_path_name

docs/2.0/recipes/custom-link-field.md
Link to the `show` page, not the `index` page.
=> fix custom link examples

docs/2.0/fields/markdown.md, docs/3.0/fields/markdown.md
In concert with https://github.com/avo-hq/avo/pull/1729, update the documentation to refer to the new editor for Markdown fields.
=> Change SimpleMDE refs to EasyMDE

docs/3.0/dynamic-filters.md
The current example in the documentation does not correctly apply the config on the dynamic filters
This PR updates the example to use `Avo::DynamicFilters`
=> Update defined? example on dynamic filters

docs/2.0/menu-editor.md, docs/3.0/menu-editor.md
I'm adding here documentation adjustments for the feature being added with https://github.com/avo-hq/avo/pull/1957.
I wasn't sure if I should add it to v3 or also v2, so I've added it in both.
=> feature: add docs about params on resource menu item

docs/3.0/avo-2-avo-3-upgrade.md
The `heading` field has changed to a field type from v2 to v3, but this is not mentioned in the upgrade guide anywhere.
I've added a section here with examples of upgrading from text and from HTML.
=> Add "`heading` has become a field type" section to upgrade guide

docs/2.0/faq.md, docs/2.0/index.md, docs/3.0/faq.md, docs/3.0/index.md
The heroku link is not working and another demo app seems to be in operation, so I replaced the link.Please check it out.
ref. https://github.com/avo-hq/avo/pull/1954
=> Update live demo app URL in documentation to point to main.avodemo.com

docs/2.0/associations.md
Fix typo in example of using link_to_child_resource parameter for field of type has_many
=> Fix typo in example of using link_to_child_resource for field has_many

docs/3.0/customization.md
I ran into an issue for a resource using friendly id 
When using a custom action on a model then the id is an array and friendly `find` method does not support array so we need to manually handle that 
Also the doc uses the `find!` method but this is not a friendly method only `find` exists
=> Update the doc for friendly id to support arrays of slugs

docs/3.0/customization.md
In the switch from avo 2 to avo 3, the way to get a path to a dashboard changed from:
avo.dashboard_path(:dashy)
to 
avo_dashboards.dashboard_path(:dashy)
But the documentation wasn't updated.
=> Correct the way to get a dashboard path

docs/2.0/fields/trix.md, docs/3.0/fields/trix.md
This PR just fix a typo in the trix field documentation 😉
=> fix: typo in trix field documentation

docs/3.0/authorization.md
Updated the Avo authorization documentation to reflect the default configuration and provide clear instructions for enabling the Pundit client for authorization. Included information on alternatives and warnings for manual setup.
Fixes [#2475](https://github.com/avo-hq/avo/issues/2475)
=> fix: Updated Avo authorization documentation

docs/3.0/customization.md
https://github.com/avo-hq/avo/pull/2537
=> fix: rename instantclick to instant_click

docs/3.0/fields/select.md
I was setting `options` on a select field with an array of arrays , (ie `[["Option 1", "one"], ["Option 2", "two"]]` etc) and was wondering why `display_with_value` wasn't working. I then noticed the inconsistency in the docs and that the implementation only checks `display_value` on option hashes and enums
=> Small issue with `select` field docs and additional clarification

docs/3.0/testing.md
In the action example, the expected keyword is `query`, but in the spec itself, it's `records`. This does not currently work and we had to figure out that we need to use `query` in both cases.
Additionally, we had to use the full namespace so that the spec was runnable.
=> Testing Docs: Use `query` in both cases

docs/3.0/guides/rails-authentication-scaffold.md
Since `require_authentication` runs in the Avo context, it's necessary to delegate the `new_session_path` to the `main_app` to ensure proper routing.
Reported here: https://discord.com/channels/740892036978442260/1326073334982774887
1. `rails _8.0.1_ new avo_auth`
2. `bin/rails app:template LOCATION='https://avohq.io/app-template'`
3. `bin/rails generate authentication`
4. `bin/rails db:migrate`
5. Follow https://docs.avohq.io/3.0/guides/rails-authentication-scaffold.html#authentication-using-rails-scaffold
6. `bin/dev`
7. visit http://localhost:3000/avo
8. Notice error:
9. Insert `delegate :new_session_path, to: :main_app` on `app/controllers/avo/application_controller.rb`
10. visit http://localhost:3000/avo
11. Works as expected.
=> new_session_path delegation for authentication

docs/3.0/authorization.md
This will help to keep authorization in policy class instead of writing it randomly in resources.
=> Add documentation for using resource's policy class to authorize custom action

docs/3.0/stimulus-integration.md, docs/4.0/stimulus-integration.md
This PR fixes the grammatical error in the``` StimulusJS in action``` section of the Stimulus JS integration page
=> Fix grammatical error on Stimulus JS integration page

docs/3.0/menu-editor.md
`exclude` didn't work and I noticed in the `avo-menu` gem's code that the argument should be `except`.
=> Use correct argument to exclude resources/dashboards in menu
